Repository University-MakeUs-Challenge-ProductTeam/Official-Web-FE, pull requests merged in 2024-11, with the labels that each got.

#5 Feature/#4 메인 페이지 제작
  next.config.mjs
  package.json
  public/images/UMC_LOGO.png
  public/images/logo.png
  src/app/_components/Banner/index.tsx
  src/app/_components/FifthBanner/_components/Slider/index.tsx
  src/app/_components/FifthBanner/_components/SliderList/index.tsx
  src/app/_components/FifthBanner/index.tsx
  src/app/_components/FourthBanner/index.tsx
  src/app/_components/SecondBanner/index.tsx
  src/app/_components/SixthBanner/index.tsx
  src/app/_components/ThirdBanner/index.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/shared/api/axios-instance.ts
  src/shared/api/main.ts
  src/shared/components/Button/index.tsx
  src/shared/components/Typography/index.tsx
  src/shared/constants/querykeys/project.ts
  src/shared/hooks/queries/useGetAllProjects.ts
  src/shared/hooks/queries/useGetMainActivity.ts
  src/shared/models/font.ts
  src/shared/styles/index.ts
  src/shared/styles/swiper.css
  src/shared/types/api/academy.ts
  src/shared/types/api/project.ts
  src/shared/types/dtos/academy.ts
  src/shared/types/dtos/project.ts
  src/shared/types/query/common.ts
  src/shared/utils/style.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature

#6 Feature/#3 모집안내 페이지 구현 & API 연결
  src/app/recruitment/_components/ActivityBox/index.tsx
  src/app/recruitment/_components/FaqAccordions/index.tsx
  src/app/recruitment/_components/PartAndSkill/index.tsx
  src/app/recruitment/_components/RecruitmentSchedule/index.tsx
  src/app/recruitment/_components/ScheduleBox/index.tsx
  src/app/recruitment/_components/SchoolDropdown/index.tsx
  src/app/recruitment/_components/StaffBox/index.tsx
  src/app/recruitment/page.tsx
  src/shared/api/recruitment.ts
  src/shared/api/shcool.ts
  src/shared/components/Accordion/AccordionItem/index.tsx
  src/shared/components/Accordion/AccordionProvider/index.tsx
  src/shared/components/Accordion/accordion-context.ts
  src/shared/components/Accordion/index.tsx
  src/shared/components/Dropdown/DropdownMenu/index.tsx
  src/shared/constants/FaqContent.ts
  src/shared/constants/activityContent.ts
  src/shared/constants/querykeys/project.ts
  src/shared/constants/recruitment.ts
  src/shared/types/api/requirementTypes.ts
  src/shared/types/api/schoolTypes.ts
  src/shared/types/recruitmentDto.ts
  src/shared/types/schoolDto.ts
  src/shared/utils/date.ts
Labels: ✨ Feature

#9 Feature/#7 후원신청 폼 페이지 구현
  eslint/typescript.js
  package.json
  src/app/sponser/_components/Form/index.tsx
  src/app/sponser/page.tsx
  src/shared/api/sponsor.ts
  src/shared/components/Input/index.tsx
  src/shared/components/LoadingSpinner/index.tsx
  src/shared/components/TextArea/index.tsx
  src/shared/hooks/queries/usePostSponsorResponse.ts
  src/shared/hooks/useSingleRequest.ts
  src/shared/types/dtos/sponsor.ts
  yarn.lock
Labels: ✨ Feature

#10 Feature/#8 소개 페이지 구현
  src/app/introduction/_components/FifthBanner/_components/StaffProfile/index.tsx
  src/app/introduction/_components/FifthBanner/index.tsx
  src/app/introduction/_components/FirstBanner/index.tsx
  src/app/introduction/_components/FourthBanner/index.tsx
  src/app/introduction/_components/SecondBanner/_components/SchoolSlider/index.tsx
  src/app/introduction/_components/SecondBanner/index.tsx
  src/app/introduction/_components/ThirdBanner/index.tsx
  src/app/introduction/page.tsx
  src/app/project/[id]/page.tsx
  src/app/project/_components/ProjectCard/index.tsx
  src/app/project/page.tsx
  src/shared/api/event.ts
  src/shared/api/part.ts
  src/shared/api/staff.ts
  src/shared/constants/activityContent.ts
  src/shared/constants/introductionContent.ts
  src/shared/constants/querykeys/project.ts
  src/shared/types/api/event.ts
  src/shared/types/api/partTypes.ts
  src/shared/types/api/staff.ts
  src/shared/types/eventDtos.ts
  src/shared/types/partDtos.ts
  src/shared/types/staffDto.ts
Labels: ✨ Feature

#15 Feature/#14 서버 변경사항 LogoImage 변경 대응
  src/app/_components/FifthBanner/_components/Slider/index.tsx
  src/app/_components/FifthBanner/_components/SliderList/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#18 feature/#17 애니메이션 추가, 및 주요활동 UI 수정
  package.json
  src/app/_components/Banner/index.tsx
  src/app/_components/FourthBanner/index.tsx
  src/app/_components/SecondBanner/index.tsx
  src/app/sponser/_components/Form/index.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Style

#22 feature/#21 프로젝트 API 요청 에러 수정 & 메인화면 오타 수정
  next.config.mjs
  src/app/_components/FifthBanner/index.tsx
Labels: 🐞 BugFix

#25 deploy: V1.0.0
  package.json
Labels: 🌏 Deploy

#30 feature/#29: 활동 정보 요청 axiosInstance 적용
  src/app/recruitment/_components/ActivityBox/index.tsx
  src/shared/api/recruitment.ts
  src/shared/constants/querykeys/project.ts
Labels: 🐞 BugFix

#32 feature/#31 반응형 디자인 수정
  public/images/그릿지.jpg
  public/images/너디너리.png
  public/images/컴공선배.jpg
  src/app/_components/FifthBanner/index.tsx
  src/app/_components/SixthBanner/index.tsx
  src/app/_components/ThirdBanner/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Logo/index.tsx
  src/shared/components/Navbar/index.tsx
  src/shared/components/UserMenu/index.tsx
Labels: 🐞 BugFix, 🎨 Style

#35 feature/#34 추가 요구사항 반영
  src/app/project/page.tsx
  src/shared/components/Navbar/index.tsx
  src/shared/constants/activityContent.ts
  src/shared/types/dtos/academy.ts
Labels: 🌏 Deploy, 🎨 Style

#36 deploy v1.0.0
  src/app/project/page.tsx
  src/shared/components/Navbar/index.tsx
  src/shared/constants/activityContent.ts
  src/shared/types/dtos/academy.ts
Labels: 🌏 Deploy

#39 chore: SchoolData type logoImageUrl 추가
  src/shared/types/schoolDto.ts
Labels: ✨ Feature, 🎨 Style

#40 feature/#37 추가 요구사항 반영
  public/images/그릿지.jpg
  public/images/그릿지.png
  public/images/소프트스퀘어드.png
  src/app/_components/SixthBanner/index.tsx
  src/shared/constants/activityContent.ts
  src/shared/types/dtos/academy.ts
  src/shared/types/eventDtos.ts
Labels: 🌏 Deploy, ✨ Feature

#41 V1.0.0 deploy
  public/images/그릿지.jpg
  public/images/그릿지.png
  public/images/소프트스퀘어드.png
  src/app/_components/SixthBanner/index.tsx
  src/shared/constants/activityContent.ts
  src/shared/types/dtos/academy.ts
  src/shared/types/eventDtos.ts
  src/shared/types/schoolDto.ts
Labels: 🌏 Deploy

#43 feature/#42 추가 요구사항 반영 및 기타 버그 fix
  src/app/_components/FifthBanner/_components/Slider/index.tsx
  src/app/_components/FourthBanner/index.tsx
  src/app/_components/ThirdBanner/index.tsx
  src/app/introduction/_components/FifthBanner/_components/StaffProfile/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#48 Feature/#47 학교 슬라이드 로고 추가 & 후원사 페이지 분리
  src/app/_components/FifthBanner/_components/Slider/index.tsx
  src/app/introduction/_components/SecondBanner/_components/SchoolSlider/index.tsx
  src/app/sponser/_components/FirstBanner/index.tsx
  src/app/sponser/_components/SecondBanner/index.tsx
  src/app/sponser/_components/ThirdBanner/index.tsx
  src/app/sponser/apply/page.tsx
  src/app/sponser/page.tsx
  src/shared/api/sponsor.ts
  src/shared/constants/querykeys/project.ts
  src/shared/types/api/sponsor.ts
Labels: ✨ Feature, 🎨 Style

#50 [Fix] logoImageUrl 서버 변경 대응
  src/app/introduction/_components/SecondBanner/_components/SchoolSlider/index.tsx
Labels: 🐞 BugFix

#52 deploy v1.0.0
  src/app/_components/ThirdBanner/index.tsx
  src/app/layout.tsx
Labels: 🌏 Deploy
